fix: call presentPaywallIfNeeded when needed
RevenueCat/purchases-flutter pull request #1066
Opened 2024-05-08 03:53 UTC by danjocha

Thank you for contributing to Purchases. Before pressing the "Create Pull Request" button, please provide the following:

  - [x] A description about what and why you are contributing, even if it's trivial.
  - Call the `presentPaywallIfNeeded` method when the `requiredEntitlementIdentifier` is not empty

  - [x] The issue number(s) or PR number(s) in the description if you are contributing in response to those.
[https://github.com/RevenueCat/purchases-flutter/issues/1065](url)
  - [ ] If applicable, unit tests.

2024-05-08 10:20 UTC, vegaro requested changes
Thanks for opening, that makes sense, good catch

Let us know if you prefer us taking care of the changes and we can get the bugfix released soon

2024-05-08 10:20 UTC, vegaro commented on purchases_ui_flutter/ios/Classes/PurchasesUiFlutterPlugin.swift
>              if let requiredEntitlementIdentifier {
I think we can remove this `if let`

2024-05-08 10:20 UTC, vegaro commented on purchases_ui_flutter/ios/Classes/PurchasesUiFlutterPlugin.swift
> -            if let offeringIdentifier {
we still need this

2024-05-09 01:16 UTC, danjocha commented
@vegaro I just pushed another commit. I removed the incorrect `if let`, let me know if this code works or if you want to take it from here. 

Happy to contribute wherever I can

2024-05-09 19:27 UTC, vegaro approved these changes

2024-05-09 19:27 UTC, vegaro commented
Thanks @danjocha I will take care of merging this

2024-05-09 19:28 UTC, merged